### ISSUE TITLE
On iPhone X toolbar is too narrow

### ISSUE THREAD

**Issue by marcoliverteschke** [monicahq/chandler#242]
Hi!

On iPhone X the clock and networking icons take up the upper third of the toolbar and the notch reaches into the search field.

I think it’s also because of the clock that the back-arrow is kind of hard to tap successfully.

Marc

**Comment by Mokto** [comment]
Hi @marcoliverteschke ,

Thanks for your feedback. Could you post a screenshots on the issue please ?

Thanks !

**Comment by Mokto** [comment]
@marcoliverteschke this should be fixed.

To test this, can you try to `enable advanced features` in your settings please ?

It will download silently the new app in the backend when you launch the app again. Next reboot the app will be installed.

Let me know if it works, so that I can push this update to everyone !

Thanks.

**Comment by marcoliverteschke** [comment]
Yes, this is much better! Thank you!

**Comment by marcoraddatz** [comment]
Hi, also followed you instructions and the update fixes some layout issues. However, I still do not have any buttons on the upper right, thus I cannot add activities, calls or similar. (Like shown here: https://www.monicahq.com/img/posts/2018-05-28-mobile-app.png). Might this be an issue or an restriction because I'm using the free plan?

![img_0356-2](https://user-images.githubusercontent.com/248815/40920495-0443b6e8-680d-11e8-898a-dfcd98ba86c3.png)

**Comment by Mokto** [comment]
@marcoliverteschke Actually the feature has not been implemented (yet) ;)

The only things you can currently edit/add are notes.

**Comment by marcoraddatz** [comment]
Thanks for clarifying! Also, thanks for your work!
